// <auto-generated />
namespace MyEshop.DataLayer.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class migChangeProductGroup : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(migChangeProductGroup));
        
        string IMigrationMetadata.Id
        {
            get { return "202012230758394_mig-ChangeProductGroup"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
