// <auto-generated />
namespace MyEshop.DataLayer.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class migChangeProductSecond : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(migChangeProductSecond));
        
        string IMigrationMetadata.Id
        {
            get { return "202012230754060_mig-ChangeProduct-Second"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
