// <auto-generated />
namespace MyEshop.DataLayer.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class migProductModels : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(migProductModels));
        
        string IMigrationMetadata.Id
        {
            get { return "202012021632167_mig-ProductModels"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
